/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package R18_G2_ASM1;

import java.util.HashMap;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        MoneyStack m = new MoneyStack();
        ATM a = new ATM("Canberra", m);
        a.run();
    }
}