/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R18_G2_ASM1;

public class App {
    public static void main(String[] args) {
        ATM a = new ATM("Canberra");
        a.run();
    }
}
